### ISSUE TITLE
is it possible to provide the data files (train_data.csv)

### ISSUE THREAD

**Issue by siruil** [yunzhuangshen/MLPH#1]
Hi,

Thanks for providing the code! I tried to run the code "01-train-and-optimize.py" but got the error "can't open input file ../train_data/train_data.csv". I wonder if there's a separate train_data.csv file not provided, and whether it's possible to share the data file.

Thanks,

Sirui

**Comment by yunzhuangshen** [comment]
Hi Sirui,

I will look at this issue at my earliest convenience and will let you know.  

BTW, are you running it on windows? The code runs ok on my Ubuntu 18.04. The issue may lie in the incorrect path configuration to the training data. 

To answer the question, the training data is collected on the fly by running the code, and it is stored in the file 'train_data.csv'. 

Yunzhuang

**Comment by siruil** [comment]
Hi Yunzhuang,

Thanks for the quick reply and the detailed explanation! I'm running on ubuntu 18.04 too (with python 3.8.5, gurobi 9.03, and openmpi-4.1.1). I looked at the error message a bit closely, and it seems like it's actually due to my system's not able to find libcurl.so.4. "libcurl.so.4: no version information available (required by /usr/bin/cmake)". I'll try to fix this myself, and I think your code should run fine after I resolve this.

Sirui
